Repository TomBursch/kitchenowl, pull requests merged in 2023-11, with the labels that each got.

#275 feat: Allow password resets and email verification
  lib/app.dart
  lib/cubits/email_confirm_cubit.dart
  lib/cubits/password_reset_cubit.dart
  lib/cubits/settings_user_cubit.dart
  lib/l10n/app_en.arb
  lib/models/user.dart
  lib/pages/analytics_page.dart
  lib/pages/email_confirm_page.dart
  lib/pages/login_page.dart
  lib/pages/password_forgot_page.dart
  lib/pages/password_reset_page.dart
  lib/pages/settings_user_email_page.dart
  lib/pages/settings_user_page.dart
  lib/pages/settings_user_password_page.dart
  lib/pages/signup_page.dart
  lib/pages/unreachable_page.dart
  lib/router.dart
  lib/services/api/user.dart
  lib/widgets/_export.dart
  lib/widgets/loading_list_tile.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#276 feat: Settle balance button in overview
  lib/cubits/expense_overview_cubit.dart
  lib/l10n/app_de.arb
  lib/l10n/app_en.arb
  lib/pages/expense_add_update_page.dart
  lib/pages/expense_overview_page.dart
Labels: enhancement

#270 Translations update from Hosted Weblate
  lib/l10n/app_da.arb
  lib/l10n/app_de.arb
  lib/l10n/app_el.arb
  lib/l10n/app_es.arb
  lib/l10n/app_fi.arb
  lib/l10n/app_fr.arb
  lib/l10n/app_it.arb
  lib/l10n/app_nl.arb
Labels: localization

#277 feat: Grid view for recipe list
  lib/cubits/recipe_list_cubit.dart
  lib/pages/household_page/recipe_list.dart
  lib/widgets/left_right_wrap.dart
  lib/widgets/recipe_card.dart
Labels: enhancement

#279 feat: Allow exclusion of expenses from overview/statistics
  lib/cubits/expense_add_update_cubit.dart
  lib/l10n/app_en.arb
  lib/models/expense.dart
  lib/pages/expense_add_update_page.dart
  lib/pages/expense_overview_page.dart
Labels: enhancement

#285 docs: fixed broken weblink
  docs/self-hosting/index.md
Labels: documentation

#281 feat: OIDC support
  assets/images/google_logo.png
  default.conf.template
  docs/img/screenshots/oidc_button.png
  docs/self-hosting/advanced.md
  docs/self-hosting/oidc.md
  lib/cubits/auth_cubit.dart
  lib/cubits/server_info_cubit.dart
  lib/cubits/settings_user_cubit.dart
  lib/enums/oidc_provider.dart
  lib/l10n/app_en.arb
  lib/main.dart
  lib/models/user.dart
  lib/pages/login_page.dart
  lib/pages/login_redirect_page.dart
  lib/pages/settings_user_linked_accounts_page.dart
  lib/pages/settings_user_page.dart
  lib/router.dart
  lib/services/api/api_service.dart
  lib/widgets/_export.dart
  lib/widgets/loading_elevated_button_icon.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#282 Translations update from Hosted Weblate
  lib/l10n/app_de.arb
  lib/l10n/app_el.arb
  lib/l10n/app_es.arb
  lib/l10n/app_fi.arb
  lib/l10n/app_fr.arb
Labels: localization

#289 fix: OIDC redirects
  lib/app.dart
  lib/enums/oidc_provider.dart
  lib/helpers/url_launcher.dart
  lib/pages/login_redirect_page.dart
  lib/pages/settings_page.dart
  lib/router.dart
Labels: bug

#290 Translations update from Hosted Weblate
  lib/l10n/app_el.arb
Labels: localization

#298 feat: Expense Overview improvements
  lib/cubits/expense_list_cubit.dart
  lib/cubits/expense_month_list_cubit.dart
  lib/cubits/expense_overview_cubit.dart
  lib/models/month_overview.dart
  lib/pages/expense_month_list_page.dart
  lib/pages/expense_overview_page.dart
  lib/pages/household_page/expense_list.dart
  lib/services/api/expense.dart
  lib/services/transactions/expense.dart
  lib/widgets/chart_bar_months.dart
  lib/widgets/chart_line_current_month.dart
  lib/widgets/chart_pie_current_month.dart
  lib/widgets/expense_item.dart
Labels: enhancement

#297 Translations update from Hosted Weblate
  lib/l10n/app_de.arb
  lib/l10n/app_el.arb
  lib/l10n/app_en.arb
  lib/l10n/app_en_AU.arb
  lib/l10n/app_es.arb
  lib/l10n/app_fi.arb
  lib/l10n/app_fr.arb
  lib/l10n/app_nl.arb
  lib/l10n/app_sv.arb
Labels: localization
