Repository TomBursch/kitchenowl, pull requests merged in 2023-10, with the labels that each got.

#255 feat: Export/import household from UI
  lib/cubits/household_add_update/household_update_cubit.dart
  lib/l10n/app_en.arb
  lib/models/import_settings.dart
  lib/services/api/import_export.dart
  lib/widgets/select_file.dart
  lib/widgets/settings_household/import_settings_dialog.dart
  lib/widgets/settings_household/sliver_household_danger_zone.dart
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: enhancement

#256 feat: Add Catalan/Valencian
  android/app/build.gradle
  android/app/src/main/res/xml/locales_config.xml
  ios/Runner/Info.plist
  lib/l10n/app_ca.arb
  lib/l10n/app_ca_valencia.arb
Labels: localization

#257 Add markdown tips
  README.md
  docs/Tips-&-Tricks/index.md
  docs/Tips-&-Tricks/markdown.md
  docs/self-hosting/index.md
Labels: documentation

#263 fix: Recipes are not scaled correctly when opened
  lib/cubits/recipe_cubit.dart
  lib/models/recipe.dart
Labels: bug

#265 feat: Simple item icon search
  fonts/Items.ttf
  generate-item-icons.py
  lib/item_icons.dart
  lib/pages/icon_selection_page.dart
Labels: enhancement

#267 feat: Improve balance overview
  lib/cubits/expense_overview_cubit.dart
  lib/l10n/app_en.arb
  lib/pages/expense_overview_page.dart
  lib/services/api/expense.dart
  lib/services/transactions/expense.dart
  lib/widgets/chart_bar_months.dart
  lib/widgets/chart_pie_current_month.dart
Labels: enhancement

#258 Translations update from Hosted Weblate
  lib/l10n/app_de.arb
  lib/l10n/app_el.arb
  lib/l10n/app_es.arb
  lib/l10n/app_fr.arb
  lib/l10n/app_id.arb
  lib/l10n/app_pl.arb
  lib/l10n/app_ru.arb
  lib/l10n/app_sv.arb
Labels: localization

#272 feat: Collapsible recent item categories
  lib/cubits/settings_cubit.dart
  lib/pages/household_page/shoppinglist.dart
  lib/pages/recipe_page.dart
  lib/pages/settings_page.dart
  lib/services/transactions/shoppinglist.dart
  lib/widgets/number_selector.dart
Labels: enhancement
