Repository TomBursch/kitchenowl, pull requests merged in 2023-08, with the labels that each got.

#138 feat: Add yields to the meal plan
  lib/cubits/item_selection_cubit.dart
  lib/cubits/planner_cubit.dart
  lib/cubits/recipe_cubit.dart
  lib/l10n/app_en.arb
  lib/models/planner.dart
  lib/pages/household_page/planner.dart
  lib/pages/item_selection_page.dart
  lib/pages/recipe_page.dart
  lib/router.dart
  lib/services/api/planner.dart
  lib/services/transactions/planner.dart
Labels: enhancement

#213 feat: Item management improvements
  lib/cubits/household_add_update/household_update_cubit.dart
  lib/cubits/item_edit_cubit.dart
  lib/l10n/app_en.arb
  lib/pages/item_page.dart
  lib/services/api/category.dart
  lib/services/api/item.dart
  lib/widgets/select_dialog.dart
  lib/widgets/settings_household/sliver_household_category_settings.dart
Labels: enhancement

#194 Translations update from Hosted Weblate
  lib/l10n/app_be.arb
  lib/l10n/app_cs.arb
  lib/l10n/app_da.arb
  lib/l10n/app_de.arb
  lib/l10n/app_el.arb
  lib/l10n/app_es.arb
  lib/l10n/app_fi.arb
  lib/l10n/app_fr.arb
  lib/l10n/app_hu.arb
  lib/l10n/app_id.arb
  lib/l10n/app_it.arb
  lib/l10n/app_nb.arb
  lib/l10n/app_nl.arb
  lib/l10n/app_pa.arb
  lib/l10n/app_pl.arb
  lib/l10n/app_pt.arb
  lib/l10n/app_ro.arb
  lib/l10n/app_ru.arb
  lib/l10n/app_sv.arb
  lib/l10n/app_tr.arb
Labels: localization

#210 feat: add Russian & Portuguese
  android/app/build.gradle
  android/app/src/main/res/xml/locales_config.xml
  ios/Runner/Info.plist
Labels: localization

#216 Translations update from Hosted Weblate
  lib/l10n/app_cs.arb
  lib/l10n/app_es.arb
  lib/l10n/app_fi.arb
  lib/l10n/app_pt.arb
  lib/l10n/app_zh_Hans.arb
Labels: localization

#217 Add Simplified Chinese
  android/app/build.gradle
  android/app/src/main/res/xml/locales_config.xml
  ios/Runner/Info.plist
Labels: localization

#230 fix: Shopping list delete multiple items offline
  lib/services/transaction.dart
  lib/services/transactions/expense.dart
Labels: bug

#231 fix: Add stronger distinction in list view
  lib/cubits/shoppinglist_cubit.dart
  lib/widgets/selectable_button_card.dart
  lib/widgets/shopping_item.dart
Labels: enhancement

#218 Translations update from Hosted Weblate
  lib/l10n/app_da.arb
  lib/l10n/app_de.arb
  lib/l10n/app_el.arb
  lib/l10n/app_fi.arb
  lib/l10n/app_fr.arb
  lib/l10n/app_it.arb
  lib/l10n/app_nl.arb
  lib/l10n/app_pl.arb
  lib/l10n/app_pt_BR.arb
  lib/l10n/app_ru.arb
  lib/l10n/app_zh.arb
Labels: localization

#232 feat: Add Portuguese (Brazil)
  android/app/build.gradle
  android/app/src/main/res/xml/locales_config.xml
  ios/Runner/Info.plist
Labels: localization
