Repository TomBursch/kitchenowl, pull requests merged in 2023-05, with the labels that each got.

#164 feat: add household leave confirmation dialog
  lib/l10n/app_de.arb
  lib/l10n/app_en.arb
  lib/pages/settings_page.dart
Labels: enhancement

#156 Translations update from Hosted Weblate
  lib/l10n/app_cs.arb
Labels: localization

#166 feat: add Czech
  android/app/build.gradle
  android/app/src/main/res/xml/locales_config.xml
  ios/Runner/Info.plist
Labels: localization

#170 docs: Add funding information
  .github/FUNDING.yml
Labels: documentation

#171 feat: Allow optional public user sign up
  lib/app.dart
  lib/cubits/auth_cubit.dart
  lib/cubits/server_info_cubit.dart
  lib/l10n/app_en.arb
  lib/pages/household_page.dart
  lib/pages/login_page.dart
  lib/pages/settings_page.dart
  lib/pages/signup_page.dart
  lib/router.dart
  lib/services/api/api_service.dart
Labels: enhancement

#173 feat: Optionally require email for signup
  lib/cubits/auth_cubit.dart
  lib/cubits/server_info_cubit.dart
  lib/cubits/settings_user_cubit.dart
  lib/l10n/app_en.arb
  lib/models/user.dart
  lib/pages/settings_user_email_page.dart
  lib/pages/settings_user_page.dart
  lib/pages/signup_page.dart
  lib/services/api/api_service.dart
  lib/services/api/user.dart
  lib/widgets/create_user_form_fields.dart
Labels: enhancement

#167 Translations update from Hosted Weblate
  lib/l10n/app_be.arb
  lib/l10n/app_cs.arb
  lib/l10n/app_da.arb
  lib/l10n/app_de.arb
  lib/l10n/app_en.arb
  lib/l10n/app_es.arb
  lib/l10n/app_fi.arb
  lib/l10n/app_fr.arb
  lib/l10n/app_hu.arb
  lib/l10n/app_id.arb
  lib/l10n/app_it.arb
  lib/l10n/app_nb.arb
  lib/l10n/app_nl.arb
  lib/l10n/app_pl.arb
  lib/l10n/app_sv.arb
  lib/l10n/app_tr.arb
Labels: localization

#174 feat: add Belarusian & Polish
  android/app/build.gradle
  android/app/src/main/res/xml/locales_config.xml
  ios/Runner/Info.plist
Labels: localization
