Repository TomBursch/kitchenowl, pull requests merged in 2023-07, with the labels that each got.

#184 feat: Allow adding household members on creation
  lib/cubits/household_add_update/household_add_cubit.dart
  lib/pages/household_add_page.dart
  lib/services/api/household.dart
Labels: enhancement

#190 feat: show user who added item and when
  lib/l10n/app_en.arb
  lib/models/item.dart
  lib/pages/item_page.dart
Labels: enhancement

#191 feat: Balance overview shows who owes whom
  lib/cubits/expense_overview_cubit.dart
  lib/l10n/app_en.arb
  lib/pages/expense_overview_page.dart
  lib/pages/household_page/expense_list.dart
  lib/widgets/chart_bar_member_distribution.dart
Labels: enhancement

#180 Translations update from Hosted Weblate
  lib/l10n/app_de.arb
  lib/l10n/app_el.arb
  lib/l10n/app_es.arb
  lib/l10n/app_fi.arb
  lib/l10n/app_fr.arb
  lib/l10n/app_hu.arb
  lib/l10n/app_it.arb
  lib/l10n/app_nl.arb
Labels: localization

#192 feat: add Greek
  android/app/build.gradle
  android/app/src/main/res/xml/locales_config.xml
  ios/Runner/Info.plist
Labels: localization

#205 feat: Ingredient pills in description
  lib/helpers/recipe_item_markdown_extension.dart
  lib/pages/recipe_page.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#208 feat: Add preference setting to resize items
  lib/cubits/settings_cubit.dart
  lib/l10n/app_en.arb
  lib/pages/household_page/planner.dart
  lib/pages/settings_page.dart
  lib/styles/dynamic.dart
  lib/widgets/sliver_item_grid_list.dart
  lib/widgets/string_item_match.dart
Labels: enhancement

#209 feat: confirm shopping list item removal
  lib/cubits/settings_cubit.dart
  lib/cubits/shoppinglist_cubit.dart
  lib/enums/views_enum.dart
  lib/l10n/app_en.arb
  lib/pages/household_page/shoppinglist.dart
  lib/pages/settings_page.dart
  lib/services/api/shoppinglist.dart
  lib/services/transactions/shoppinglist.dart
  lib/widgets/shopping_item.dart
  lib/widgets/shoppinglist_confirm_remove_fab.dart
Labels: enhancement

#207 fix: Add item to shopping list when the description is changed
  lib/services/transactions/shoppinglist.dart
Labels: bug
