Repository TomBursch/kitchenowl, pull requests merged in 2024-12, with the labels that each got.

#563 feat: Make version text selectable
  kitchenowl/lib/pages/settings_page.dart
Labels: enhancement

#566 fix: Recent items count
  kitchenowl/lib/pages/household_page/shoppinglist.dart
  kitchenowl/lib/services/transactions/shoppinglist.dart
Labels: bug

#567 fix: Extend recipe scrape timeout
  backend/app/service/recipe_scraping.py
  kitchenowl/lib/l10n/app_en.arb
  kitchenowl/lib/pages/recipe_scraper_page.dart
  kitchenowl/lib/services/api/recipe.dart
Labels: bug

#565 fix: use DOM base href for web XHRs
  kitchenowl/lib/cubits/auth_cubit.dart
  kitchenowl/lib/platform/dart_html/dart_html.dart
  kitchenowl/lib/platform/dart_html/dart_non_web.dart
  kitchenowl/lib/platform/dart_html/dart_web.dart
Labels: enhancement

#568 feat: patch env BASE_HREF into index.html
  kitchenowl/docker-entrypoint-custom.sh
Labels: enhancement

#558 Translations update from Hosted Weblate
  backend/templates/l10n/de.json
  kitchenowl/lib/l10n/app_cs.arb
  kitchenowl/lib/l10n/app_de.arb
  kitchenowl/lib/l10n/app_es.arb
  kitchenowl/lib/l10n/app_fr.arb
  kitchenowl/lib/l10n/app_kab.arb
  kitchenowl/lib/l10n/app_nl.arb
  kitchenowl/lib/l10n/app_sv.arb
Labels: localization

#569 lang: Add Kabyle
  kitchenowl/android/app/build.gradle
  kitchenowl/android/app/src/main/res/xml/locales_config.xml
  kitchenowl/ios/Runner/Info.plist
  kitchenowl/lib/l10n/app_kab.arb
Labels: localization

#573 forward args to flask from wsgi
  backend/wsgi.py
  docs/docs/reference/contributing.md
Labels: documentation

#579 fix: typo
  kitchenowl/lib/pages/analytics_page.dart
Labels: bug

#577 Add information about known backend warning to documentation
  docs/docs/reference/contributing.md
Labels: documentation

#575 Feature/ask before deleting not empty list
  kitchenowl/lib/l10n/app_en.arb
  kitchenowl/lib/pages/settings_household/household_settings_shoppinglist_page.dart
Labels: enhancement

#578 Feat: Real-time sync shopping lists addition/removal
  backend/app/controller/shoppinglist/shoppinglist_controller.py
  kitchenowl/lib/cubits/household_add_update/household_update_cubit.dart
  kitchenowl/lib/cubits/shoppinglist_cubit.dart
  kitchenowl/lib/services/api/shoppinglist.dart
Labels: enhancement

#570 Translations update from Hosted Weblate
  backend/templates/l10n/kab.json
  backend/templates/l10n/sk.json
  backend/templates/l10n/sv.json
  kitchenowl/lib/l10n/app_de.arb
  kitchenowl/lib/l10n/app_en.arb
  kitchenowl/lib/l10n/app_es.arb
  kitchenowl/lib/l10n/app_fi.arb
  kitchenowl/lib/l10n/app_sk.arb
  kitchenowl/lib/l10n/app_sv.arb
Labels: localization

#581 feat: Add Slovak
  backend/app/config.py
  kitchenowl/android/app/build.gradle
  kitchenowl/android/app/src/main/res/xml/locales_config.xml
  kitchenowl/ios/Runner/Info.plist
Labels: localization

#580 feat: Add Kabyle to backend
  backend/app/config.py
Labels: localization

#591 fix: Force switch household on request forbidden
  kitchenowl/lib/cubits/household_add_update/household_update_cubit.dart
  kitchenowl/lib/cubits/household_member_cubit.dart
  kitchenowl/lib/services/api/household.dart
  kitchenowl/lib/services/transactions/household.dart
Labels: bug

#582 Translations update from Hosted Weblate
  backend/templates/l10n/sk.json
  kitchenowl/lib/l10n/app_es.arb
  kitchenowl/lib/l10n/app_fi.arb
  kitchenowl/lib/l10n/app_hu.arb
  kitchenowl/lib/l10n/app_nl.arb
  kitchenowl/lib/l10n/app_sk.arb
Labels: localization

#604 fix: Share link adding a second slash
  kitchenowl/lib/services/api/api_service.dart
Labels: bug

#607 fix: persist forced offline mode
  kitchenowl/lib/cubits/auth_cubit.dart
Labels: bug

#609 fix: disable communication in offline mode
  kitchenowl/lib/cubits/auth_cubit.dart
Labels: bug
