Repository TomBursch/kitchenowl, pull requests merged in 2024-02, with the labels that each got.

#390 feat: Add 25 icons
  icons/icons8/aroma.svg
  icons/icons8/blankie.svg
  icons/icons8/candle.svg
  icons/icons8/christmas-tree.svg
  icons/icons8/cleaning-a-surface.svg
  icons/icons8/coconut-milk.svg
  icons/icons8/defrosting.svg
  icons/icons8/dowel.svg
  icons/icons8/fire-extinguisher.svg
  icons/icons8/firework.svg
  icons/icons8/mosquito-net.svg
  icons/icons8/paint-bucket.svg
  icons/icons8/pie.svg
  icons/icons8/pillow.svg
  icons/icons8/rose.svg
  icons/icons8/salt-shaker.svg
  icons/icons8/sandwich.svg
  icons/icons8/screw.svg
  icons/icons8/spice.svg
  icons/icons8/sport-bottle.svg
  icons/icons8/sushi.svg
  icons/icons8/taco.svg
  icons/icons8/tapas.svg
  icons/icons8/ticket.svg
  icons/icons8/tupperware.svg
  kitchenowl/fonts/Items.ttf
  kitchenowl/lib/item_icons.dart
Labels: enhancement

#393 Fix link to DockerHub
  README.md
Labels: documentation

#388 feat: Update and enhance household settings
  kitchenowl/lib/cubits/household_add_update/household_settings_items_cubit.dart
  kitchenowl/lib/enums/shoppinglist_sorting.dart
  kitchenowl/lib/helpers/build_context_extension.dart
  kitchenowl/lib/l10n/app_en.arb
  kitchenowl/lib/pages/household_add_page.dart
  kitchenowl/lib/pages/household_update_page.dart
  kitchenowl/lib/pages/icon_selection_page.dart
  kitchenowl/lib/pages/item_page.dart
  kitchenowl/lib/pages/settings_household/household_settings_category_page.dart
  kitchenowl/lib/pages/settings_household/household_settings_expense_category_page.dart
  kitchenowl/lib/pages/settings_household/household_settings_items_page.dart
  kitchenowl/lib/pages/settings_household/household_settings_shoppinglist_page.dart
  kitchenowl/lib/pages/settings_household/household_settings_tags_page.dart
  kitchenowl/lib/services/api/item.dart
  kitchenowl/lib/widgets/home_page/sliver_category_item_grid_list.dart
  kitchenowl/lib/widgets/settings_household/sliver_household_category_settings.dart
  kitchenowl/lib/widgets/settings_household/sliver_household_expense_category_settings.dart
  kitchenowl/lib/widgets/settings_household/sliver_household_feature_settings.dart
  kitchenowl/lib/widgets/settings_household/sliver_household_shoppinglist_settings.dart
  kitchenowl/lib/widgets/settings_household/sliver_household_tags_settings.dart
  kitchenowl/lib/widgets/settings_household/view_settings_list_tile.dart
  kitchenowl/lib/widgets/shopping_item.dart
  kitchenowl/lib/widgets/sliver_item_grid_list.dart
Labels: enhancement

#395 Translations update from Hosted Weblate
  backend/templates/l10n/bn.json
  backend/templates/l10n/ko.json
  backend/templates/l10n/nb_NO.json
  kitchenowl/lib/l10n/app_de.arb
  kitchenowl/lib/l10n/app_es.arb
  kitchenowl/lib/l10n/app_fi.arb
  kitchenowl/lib/l10n/app_fr.arb
  kitchenowl/lib/l10n/app_it.arb
  kitchenowl/lib/l10n/app_ko.arb
Labels: localization

#399 Translations update from Hosted Weblate
  backend/templates/l10n/ko.json
Labels: localization

#398 lang: Add Korean
  backend/app/config.py
  kitchenowl/android/app/build.gradle
  kitchenowl/android/app/src/main/res/xml/locales_config.xml
  kitchenowl/ios/Runner/Info.plist
Labels: localization

#402 fix: Modification of newly created ingredient not saved in shopping list
  backend/app/controller/item/item_controller.py
  backend/app/controller/item/schemas.py
  kitchenowl/lib/cubits/item_edit_cubit.dart
  kitchenowl/lib/pages/household_page/shoppinglist.dart
  kitchenowl/lib/pages/item_page.dart
  kitchenowl/lib/services/api/item.dart
  kitchenowl/lib/services/transactions/item.dart
  kitchenowl/lib/widgets/item_popup_menu_button.dart
Labels: bug
