Repository TomBursch/kitchenowl, pull requests merged in 2024-01, with the labels that each got.

#349 fix: Delete categories
  lib/services/api/category.dart
Labels: bug

#353 feat: Autocomplete new expense names
  lib/pages/expense_add_update_page.dart
  lib/widgets/expense_create_fab.dart
Labels: enhancement

#354 fix: Recent item description not editable
  lib/pages/household_page/shoppinglist.dart
  lib/pages/item_page.dart
  lib/widgets/home_page/sliver_category_item_grid_list.dart
  lib/widgets/sliver_item_grid_list.dart
Labels: bug

#322 Translations update from Hosted Weblate
  lib/l10n/app_fr.arb
  lib/l10n/app_nb.arb
  lib/l10n/app_nl.arb
  lib/l10n/app_sv.arb
  lib/l10n/app_vi.arb
Labels: localization

#355 feat: Add Vietnamese
  android/app/build.gradle
  android/app/src/main/res/xml/locales_config.xml
  ios/Runner/Info.plist
Labels: localization

#376 Translations update from Hosted Weblate
  backend/templates/l10n/en.json
  backend/templates/l10n/en_AU.json
  backend/templates/l10n/es.json
  backend/templates/l10n/pl.json
  backend/templates/l10n/sv.json
  kitchenowl/lib/l10n/app_ca.arb
  kitchenowl/lib/l10n/app_ca_valencia.arb
  kitchenowl/lib/l10n/app_cs.arb
  kitchenowl/lib/l10n/app_da.arb
  kitchenowl/lib/l10n/app_en.arb
  kitchenowl/lib/l10n/app_en_AU.arb
  kitchenowl/lib/l10n/app_es.arb
  kitchenowl/lib/l10n/app_hu.arb
  kitchenowl/lib/l10n/app_id.arb
  kitchenowl/lib/l10n/app_pt.arb
  kitchenowl/lib/l10n/app_pt_BR.arb
  kitchenowl/lib/l10n/app_ru.arb
  kitchenowl/lib/l10n/app_tr.arb
Labels: localization

#382 fix: Add to meal plan not showing for recipes without ingredients
  kitchenowl/lib/pages/recipe_page.dart
  kitchenowl/lib/widgets/rendering/sliver_with_pinned_footer.dart
Labels: bug

#384 fix: Parser of web recipe return 500 internal server error
  backend/app/controller/recipe/recipe_controller.py
Labels: bug

#385 fix: ingredient pill does not work with apostrophe
  kitchenowl/lib/helpers/recipe_item_markdown_extension.dart
Labels: bug

#386 lang: Add German (Switzerland)
  backend/app/config.py
  kitchenowl/android/app/build.gradle
  kitchenowl/android/app/src/main/res/xml/locales_config.xml
  kitchenowl/ios/Runner/Info.plist
Labels: localization

#381 Translations update from Hosted Weblate
  backend/templates/l10n/cs.json
  backend/templates/l10n/da.json
  backend/templates/l10n/de.json
  backend/templates/l10n/de_CH.json
  backend/templates/l10n/el.json
  backend/templates/l10n/en_AU.json
  backend/templates/l10n/es.json
  backend/templates/l10n/fi.json
  backend/templates/l10n/fr.json
  backend/templates/l10n/hu.json
  backend/templates/l10n/id.json
  backend/templates/l10n/it.json
  backend/templates/l10n/nb_NO.json
  backend/templates/l10n/nl.json
  backend/templates/l10n/pl.json
  backend/templates/l10n/pt.json
  backend/templates/l10n/pt_BR.json
  backend/templates/l10n/ru.json
  backend/templates/l10n/tr.json
  backend/templates/l10n/zh_Hans.json
  kitchenowl/lib/l10n/app_cs.arb
  kitchenowl/lib/l10n/app_it.arb
  kitchenowl/lib/l10n/app_nl.arb
  kitchenowl/lib/l10n/app_sv.arb
  kitchenowl/lib/l10n/app_tr.arb
Labels: localization

#365 Add testing for recipe_cubit
  kitchenowl/lib/cubits/item_search_cubit.dart
  kitchenowl/lib/cubits/recipe_cubit.dart
  kitchenowl/lib/cubits/recipe_list_cubit.dart
  kitchenowl/lib/pages/recipe_page.dart
  kitchenowl/lib/services/transaction_handler.dart
  kitchenowl/test/cubits/local_only_transaction_handler.dart
  kitchenowl/test/cubits/recipe_cubit_test.dart
Labels: enhancement
