Repository TomBursch/kitchenowl, pull requests merged in 2024-11, with the labels that each got.

#540 feat: Refresh shopping list on resume
  kitchenowl/lib/pages/household_page.dart
Labels: enhancement

#542 feat: Allow login with email
  backend/app/controller/auth/auth_controller.py
Labels: enhancement

#530 Translations update from Hosted Weblate
  backend/templates/l10n/fi.json
  backend/templates/l10n/nb_NO.json
  kitchenowl/lib/l10n/app_fi.arb
  kitchenowl/lib/l10n/app_nb.arb
Labels: localization

#541 feat: Improve mobile settings UX
  kitchenowl/lib/enums/views_enum.dart
  kitchenowl/lib/models/household.dart
  kitchenowl/lib/pages/household_add_page.dart
  kitchenowl/lib/pages/household_page.dart
  kitchenowl/lib/pages/household_page/_export.dart
  kitchenowl/lib/pages/household_page/household_drawer.dart
  kitchenowl/lib/pages/household_page/household_navigation_rail.dart
  kitchenowl/lib/pages/household_page/more.dart
  kitchenowl/lib/pages/household_page/profile.dart
  kitchenowl/lib/router.dart
  kitchenowl/lib/widgets/household_card.dart
  kitchenowl/lib/widgets/household_image.dart
  kitchenowl/lib/widgets/settings_household/sliver_household_feature_settings.dart
Labels: enhancement

#544 feat: Use cronet client on android (Support device certificates)
  .github/workflows/release.yml
  kitchenowl/lib/services/api/api_service.dart
  kitchenowl/linux/flutter/generated_plugins.cmake
  kitchenowl/pubspec.lock
  kitchenowl/pubspec.yaml
  kitchenowl/windows/flutter/generated_plugins.cmake
Labels: enhancement

#547 feat: Add expense descriptions
  backend/app/controller/expense/expense_controller.py
  backend/app/controller/expense/schemas.py
  backend/app/models/expense.py
  backend/app/models/expense_category.py
  backend/migrations/versions/22dbfbf4cc33_.py
  kitchenowl/lib/cubits/expense_add_update_cubit.dart
  kitchenowl/lib/cubits/expense_list_cubit.dart
  kitchenowl/lib/l10n/app_en.arb
  kitchenowl/lib/models/expense.dart
  kitchenowl/lib/models/expense_category.dart
  kitchenowl/lib/pages/expense_add_update_page.dart
  kitchenowl/lib/pages/expense_page.dart
  kitchenowl/lib/pages/household_page/expense_list.dart
  kitchenowl/lib/pages/settings_household/household_settings_expense_category_page.dart
  kitchenowl/lib/widgets/text_dialog.dart
Labels: enhancement

#548 feat: Optionally remember the last used shopping list
  kitchenowl/lib/cubits/settings_cubit.dart
  kitchenowl/lib/cubits/shoppinglist_cubit.dart
  kitchenowl/lib/l10n/app_en.arb
  kitchenowl/lib/pages/settings_page.dart
Labels: enhancement

#546 Translations update from Hosted Weblate
  backend/templates/l10n/de_CH.json
  kitchenowl/lib/l10n/app_de.arb
  kitchenowl/lib/l10n/app_de_CH.arb
  kitchenowl/lib/l10n/app_es.arb
  kitchenowl/lib/l10n/app_fi.arb
  kitchenowl/lib/l10n/app_pt.arb
  kitchenowl/lib/l10n/app_ta.arb
Labels: localization

#551 Add Tamil
  kitchenowl/android/app/build.gradle
  kitchenowl/android/app/src/main/res/xml/locales_config.xml
  kitchenowl/ios/Runner/Info.plist
Labels: localization

#555 fix: F-Droid build
  kitchenowl/android/app/proguard-rules.pro
Labels: bug
