Repository TomBursch/kitchenowl, pull requests merged in 2024-08, with the labels that each got.

#487 feat: Optionally disable username and password login
  backend/app/config.py
  backend/app/controller/auth/auth_controller.py
  docs/docs/self-hosting/advanced.md
Labels: enhancement

#488 feat: Optionally set a custom JWT refresh token expiration
  backend/app/config.py
  docs/docs/self-hosting/advanced.md
Labels: enhancement

#485 feat: Add tonal recipe back and edit buttons
  kitchenowl/lib/pages/expense_page.dart
  kitchenowl/lib/pages/recipe_page.dart
  kitchenowl/lib/widgets/_export.dart
  kitchenowl/lib/widgets/flexible_image_space_bar.dart
  kitchenowl/lib/widgets/loading_icon_button.dart
  kitchenowl/lib/widgets/sliver_image_app_bar.dart
Labels: enhancement

#494 fix: Use correct application specific directories
  kitchenowl/lib/services/storage/temp_storage.dart
  kitchenowl/lib/services/storage/transaction_storage.dart
Labels: bug

#493 fix: Enforce order of transactions
  kitchenowl/lib/services/transaction_handler.dart
Labels: bug

#492 feat: List remaining items for shopping lists
  backend/app/controller/shoppinglist/schemas.py
  backend/app/controller/shoppinglist/shoppinglist_controller.py
  kitchenowl/lib/cubits/item_edit_cubit.dart
  kitchenowl/lib/cubits/planner_cubit.dart
  kitchenowl/lib/cubits/recipe_cubit.dart
  kitchenowl/lib/cubits/shoppinglist_cubit.dart
  kitchenowl/lib/models/item.dart
  kitchenowl/lib/models/shoppinglist.dart
  kitchenowl/lib/pages/household_page/planner.dart
  kitchenowl/lib/pages/household_page/shoppinglist.dart
  kitchenowl/lib/services/api/shoppinglist.dart
  kitchenowl/lib/services/storage/mem_storage.dart
  kitchenowl/lib/services/storage/temp_storage.dart
  kitchenowl/lib/services/transaction.dart
  kitchenowl/lib/services/transactions/shoppinglist.dart
  kitchenowl/lib/widgets/shopping_list/shopping_list_choice_chip.dart
Labels: enhancement

#498 feat: Search expenses
  backend/app/controller/expense/expense_controller.py
  backend/app/controller/expense/schemas.py
  kitchenowl/lib/cubits/expense_list_cubit.dart
  kitchenowl/lib/pages/household_page/expense_list.dart
  kitchenowl/lib/pages/household_page/planner.dart
  kitchenowl/lib/services/api/expense.dart
  kitchenowl/lib/services/transactions/expense.dart
  kitchenowl/lib/widgets/_export.dart
  kitchenowl/lib/widgets/choice_scroll.dart
  kitchenowl/lib/widgets/kitchenowl_search_anchor.dart
Labels: enhancement

#500 Fix Self-Hosted docs url
  README.md
Labels: documentation
