Repository TomBursch/kitchenowl, pull requests merged in 2024-04, with the labels that each got.

#373 docs: Single container install instructions
  docker-compose-postgres.yml
  docker-compose-rabbitmq.yml
  docker-compose-single.yml
  docker-compose.yml
  docs/self-hosting/advanced.md
  docs/self-hosting/index.md
  docs/self-hosting/migration.md
  docs/self-hosting/reverse-proxy.md
Labels: documentation

#435 fix: Drastically improve initial app load with many recipes
  backend/app/models/recipe.py
  kitchenowl/lib/cubits/recipe_list_cubit.dart
Labels: bug

#425 Translations update from Hosted Weblate
  backend/templates/l10n/da.json
  backend/templates/l10n/nb_NO.json
  backend/templates/l10n/pl.json
  backend/templates/l10n/sv.json
  kitchenowl/lib/l10n/app_da.arb
  kitchenowl/lib/l10n/app_nb.arb
  kitchenowl/lib/l10n/app_pl.arb
  kitchenowl/lib/l10n/app_ro.arb
  kitchenowl/lib/l10n/app_ru.arb
Labels: localization
