Repository TomBursch/kitchenowl, pull requests merged in 2024-03, with the labels that each got.

#404 feat: Categorize recent items #149
  kitchenowl/lib/pages/household_page/shoppinglist.dart
  kitchenowl/lib/widgets/home_page/sliver_category_item_grid_list.dart
Labels: enhancement

#401 Translations update from Hosted Weblate
  backend/templates/l10n/ca.json
  backend/templates/l10n/de.json
  backend/templates/l10n/de_CH.json
  backend/templates/l10n/es.json
  backend/templates/l10n/he.json
  backend/templates/l10n/lt.json
  backend/templates/l10n/ru.json
  backend/templates/l10n/tr.json
  backend/templates/l10n/uk.json
  kitchenowl/lib/l10n/app_ca.arb
  kitchenowl/lib/l10n/app_de.arb
  kitchenowl/lib/l10n/app_es.arb
  kitchenowl/lib/l10n/app_he.arb
  kitchenowl/lib/l10n/app_lt.arb
  kitchenowl/lib/l10n/app_pt.arb
  kitchenowl/lib/l10n/app_ro.arb
  kitchenowl/lib/l10n/app_ru.arb
  kitchenowl/lib/l10n/app_tr.arb
  kitchenowl/lib/l10n/app_uk.arb
Labels: localization

#409 lang: Add Hebrew
  backend/app/config.py
  kitchenowl/android/app/build.gradle
  kitchenowl/android/app/src/main/res/xml/locales_config.xml
  kitchenowl/ios/Runner/Info.plist
Labels: localization

#408 lang: Add Ukrainian
  backend/app/config.py
  kitchenowl/android/app/build.gradle
  kitchenowl/android/app/src/main/res/xml/locales_config.xml
  kitchenowl/ios/Runner/Info.plist
Labels: localization

#412 lang: Add Lithuanian
  backend/app/config.py
  kitchenowl/android/app/build.gradle
  kitchenowl/android/app/src/main/res/xml/locales_config.xml
  kitchenowl/ios/Runner/Info.plist
Labels: localization

#418 Remove jsoncpp dependency
  .github/workflows/release.yml
  kitchenowl/debian/kitchenowl/DEBIAN/control
  kitchenowl/fedora/kitchenowl.spec
Labels: bug
