Repository TomBursch/kitchenowl, pull requests merged in 2025-03, with the labels that each got.

#669 Translations update from Hosted Weblate
  backend/templates/l10n/da.json
  backend/templates/l10n/pl.json
  backend/templates/l10n/pt_BR.json
  backend/templates/l10n/ro.json
  backend/templates/l10n/sk.json
  backend/templates/l10n/zh_Hans.json
  kitchenowl/lib/l10n/app_da.arb
  kitchenowl/lib/l10n/app_de.arb
  kitchenowl/lib/l10n/app_ja.arb
  kitchenowl/lib/l10n/app_pl.arb
  kitchenowl/lib/l10n/app_pt.arb
  kitchenowl/lib/l10n/app_pt_BR.arb
  kitchenowl/lib/l10n/app_sk.arb
  kitchenowl/lib/l10n/app_zh.arb
Labels: localization

#673 Add Japanese
  kitchenowl/android/app/build.gradle
  kitchenowl/android/app/src/main/res/xml/locales_config.xml
  kitchenowl/ios/Runner/Info.plist
Labels: localization

#680 Fix Ingredients with multiple amounts in the description causes an error when merging
  backend/app/util/description_merger.py
  backend/app/util/description_splitter.py
  backend/tests/util/test_description_merger.py
  backend/tests/util/test_description_splitter.py
Labels: bug

#687 Fix enter canceling search
  kitchenowl/lib/pages/household_page/shoppinglist.dart
  kitchenowl/lib/pages/item_search_page.dart
Labels: bug

#685 Datetime planner: server
  backend/app/controller/planner/planner_controller.py
  backend/app/controller/planner/schemas.py
  backend/app/models/planner.py
  backend/app/models/recipe.py
  backend/migrations/versions/1d3c1e2061f6_datetime_in_planner.py
  backend/tests/api/conftest.py
  backend/tests/api/test_api_planner.py
Labels: enhancement

#675 Translations update from Hosted Weblate
  backend/templates/l10n/el.json
  backend/templates/l10n/he.json
  backend/templates/l10n/pl.json
  backend/templates/l10n/sk.json
  backend/templates/l10n/sl.json
  kitchenowl/lib/l10n/app_fi.arb
  kitchenowl/lib/l10n/app_he.arb
  kitchenowl/lib/l10n/app_pl.arb
  kitchenowl/lib/l10n/app_sl.arb
Labels: localization

#694 Add Slovenian
  backend/app/config.py
  kitchenowl/android/app/build.gradle
  kitchenowl/android/app/src/main/res/xml/locales_config.xml
  kitchenowl/ios/Runner/Info.plist
Labels: localization
