Repository TomBursch/kitchenowl, pull requests merged in 2025-02, with the labels that each got.

#640 chore: update github actions/upload-artifact
  .github/workflows/tests.yaml
Labels: dependencies

#631 fix: Backend startup with BASE_HREF set
  backend/entrypoint.sh
Labels: bug

#619 docs: Add OpenRouter instructions, LLM variables
  docs/docs/self-hosting/advanced.md
  docs/docs/self-hosting/ingredient_parsing.md
Labels: documentation

#642 fix: enable SMTP TLS
  backend/app/service/mail.py
  docs/docs/self-hosting/advanced.md
Labels: enhancement

#647 Sort planner by weekday relative to the current day
  kitchenowl/lib/l10n/app_de.arb
  kitchenowl/lib/l10n/app_en.arb
  kitchenowl/lib/l10n/app_es.arb
  kitchenowl/lib/pages/household_page/planner.dart
  kitchenowl/lib/pages/recipe_page.dart
Labels: enhancement

#606 Translations update from Hosted Weblate
  backend/templates/l10n/fr.json
  backend/templates/l10n/pt_BR.json
  backend/templates/l10n/ru.json
  backend/templates/l10n/ta.json
  kitchenowl/lib/l10n/app_de_CH.arb
  kitchenowl/lib/l10n/app_es.arb
  kitchenowl/lib/l10n/app_fi.arb
  kitchenowl/lib/l10n/app_fr.arb
  kitchenowl/lib/l10n/app_it.arb
  kitchenowl/lib/l10n/app_nl.arb
  kitchenowl/lib/l10n/app_pt_BR.arb
  kitchenowl/lib/l10n/app_ro.arb
  kitchenowl/lib/l10n/app_ru.arb
  kitchenowl/lib/l10n/app_sk.arb
  kitchenowl/lib/l10n/app_ta.arb
Labels: localization

#651 Add Tamil default items option
  backend/app/config.py
Labels: localization

#650 fix: Local recipe scraping
  backend/app/service/recipe_scraping.py
Labels: bug

#645 fix: Make API-Service more robust to network outages
  kitchenowl/lib/services/api/api_service.dart
Labels: bug

#655 Translations update from Hosted Weblate
  kitchenowl/lib/l10n/app_nl.arb
  kitchenowl/lib/l10n/app_ru.arb
Labels: localization

#665 Frontend round household member balance
  kitchenowl/lib/models/member.dart
Labels: bug

#664 Added caddy example to docs
  docs/docs/self-hosting/reverse-proxy.md
Labels: documentation

#661 Translations update from Hosted Weblate
  backend/templates/l10n/pt.json
  backend/templates/l10n/ro.json
  kitchenowl/lib/l10n/app_pt.arb
  kitchenowl/lib/l10n/app_ro.arb
Labels: localization

#667 Add Romanian household language
  backend/app/config.py
Labels: localization

#666 Fix use self hosted canvas kit
  .github/workflows/release.yml
  Dockerfile
  kitchenowl/Dockerfile
Labels: bug

#668 Fix: Viewing planned meals with different portions not adjusting
  kitchenowl/lib/cubits/recipe_cubit.dart
  kitchenowl/lib/models/recipe.dart
  kitchenowl/lib/pages/recipe_page.dart
Labels: bug
