Repository TomBursch/kitchenowl, pull requests merged in 2025-05, with the labels that each got.

#733 fix: Fixed color selection issues
  kitchenowl/lib/cubits/expense_category_add_update_cubit.dart
  kitchenowl/lib/widgets/kitchenowl_color_picker_dialog.dart
Labels: bug

#731 fix: Expense overview - Total for selected month is colored opposite than it should be
  kitchenowl/lib/pages/expense_overview_page.dart
Labels: bug

#717 Translations update from Hosted Weblate
  backend/templates/l10n/ar.json
  backend/templates/l10n/cs.json
  backend/templates/l10n/da.json
  backend/templates/l10n/pt.json
  kitchenowl/lib/l10n/app_cs.arb
  kitchenowl/lib/l10n/app_da.arb
  kitchenowl/lib/l10n/app_de.arb
  kitchenowl/lib/l10n/app_fr.arb
  kitchenowl/lib/l10n/app_it.arb
  kitchenowl/lib/l10n/app_pl.arb
  kitchenowl/lib/l10n/app_ru.arb
  kitchenowl/lib/l10n/app_sk.arb
  kitchenowl/lib/l10n/app_sv.arb
Labels: localization

#729 docs: Updated backend contributing docs
  docs/docs/reference/contributing.md
Labels: documentation

#736 Translations update from Hosted Weblate
  backend/templates/l10n/pt_BR.json
  backend/templates/l10n/sk.json
  kitchenowl/lib/l10n/app_ar.arb
  kitchenowl/lib/l10n/app_pt.arb
Labels: localization

#745 Translations update from Hosted Weblate
  kitchenowl/lib/l10n/app_kab.arb
  kitchenowl/lib/l10n/app_ro.arb
Labels: localization
