Repository TomBursch/kitchenowl, pull requests merged in 2025-06, with the labels that each got.

#762 Use UTC for planner everywhere
  backend/app/controller/planner/planner_controller.py
  backend/app/models/planner.py
  backend/tests/api/conftest.py
  kitchenowl/lib/cubits/planner_cubit.dart
  kitchenowl/lib/models/planner.dart
  kitchenowl/lib/pages/household_page/planner.dart
  kitchenowl/lib/pages/recipe_page.dart
Labels: bug

#787 Fix warning when base_href is set
  backend/entrypoint.sh
  kitchenowl/docker-entrypoint-custom.sh
Labels: bug

#789 Feat: Add reporting mechanism
  backend/app/api/register_controller.py
  backend/app/controller/__init__.py
  backend/app/controller/report/__init__.py
  backend/app/controller/report/report_controller.py
  backend/app/controller/report/schemas.py
  backend/app/models/__init__.py
  backend/app/models/recipe.py
  backend/app/models/report.py
  backend/app/models/token.py
  backend/app/models/user.py
  backend/migrations/versions/aa5d56fe28bb_.py
  kitchenowl/lib/l10n/app_en.arb
  kitchenowl/lib/models/report.dart
  kitchenowl/lib/pages/recipe_page.dart
  kitchenowl/lib/pages/reports_list_page.dart
  kitchenowl/lib/pages/settings_page.dart
  kitchenowl/lib/services/api/report.dart
  kitchenowl/lib/widgets/report_dialog.dart
  kitchenowl/lib/widgets/settings_household/update_member_bottom_sheet.dart
  kitchenowl/lib/widgets/text_dialog.dart
Labels: enhancement

#754 Translations update from Hosted Weblate
  backend/templates/l10n/de.json
  backend/templates/l10n/en.json
  backend/templates/l10n/fi.json
  kitchenowl/lib/l10n/app_de.arb
  kitchenowl/lib/l10n/app_es.arb
  kitchenowl/lib/l10n/app_fi.arb
  kitchenowl/lib/l10n/app_hr.arb
  kitchenowl/lib/l10n/app_kk.arb
  kitchenowl/lib/l10n/app_ru.arb
  kitchenowl/lib/l10n/app_sk.arb
Labels: localization

#794 Add Croatian
  kitchenowl/android/app/build.gradle
  kitchenowl/android/app/src/main/res/xml/locales_config.xml
  kitchenowl/ios/Runner/Info.plist
Labels: localization

#795 Add Kazakh
  kitchenowl/android/app/build.gradle
  kitchenowl/android/app/src/main/res/xml/locales_config.xml
  kitchenowl/ios/Runner/Info.plist
Labels: localization

#803 feat: support JWT_SECRET_KEY_FILE for secure secret injection
  backend/app/config.py
Labels: enhancement

#805 feat: Support _FILE variants for all secrets as outlined in feature request #576
  backend/app/config.py
  backend/app/service/mail.py
  docs/docs/self-hosting/advanced.md
Labels: enhancement

#798 Translations update from Hosted Weblate
  backend/templates/l10n/cs.json
  backend/templates/l10n/es.json
  backend/templates/l10n/fr.json
  backend/templates/l10n/it.json
  backend/templates/l10n/nl.json
  backend/templates/l10n/sk.json
  backend/templates/l10n/ta.json
  backend/templates/l10n/uk.json
  kitchenowl/lib/l10n/app_bg.arb
  kitchenowl/lib/l10n/app_ca.arb
  kitchenowl/lib/l10n/app_cs.arb
  kitchenowl/lib/l10n/app_da.arb
  kitchenowl/lib/l10n/app_de.arb
  kitchenowl/lib/l10n/app_de_CH.arb
  kitchenowl/lib/l10n/app_el.arb
  kitchenowl/lib/l10n/app_es.arb
  kitchenowl/lib/l10n/app_fi.arb
  kitchenowl/lib/l10n/app_fr.arb
  kitchenowl/lib/l10n/app_hu.arb
  kitchenowl/lib/l10n/app_it.arb
  kitchenowl/lib/l10n/app_nb.arb
  kitchenowl/lib/l10n/app_nl.arb
  kitchenowl/lib/l10n/app_pl.arb
  kitchenowl/lib/l10n/app_pt.arb
  kitchenowl/lib/l10n/app_ro.arb
  kitchenowl/lib/l10n/app_ru.arb
  kitchenowl/lib/l10n/app_sk.arb
  kitchenowl/lib/l10n/app_sl.arb
  kitchenowl/lib/l10n/app_sv.arb
  kitchenowl/lib/l10n/app_ta.arb
  kitchenowl/lib/l10n/app_tr.arb
  kitchenowl/lib/l10n/app_uk.arb
  kitchenowl/lib/l10n/app_zh.arb
Labels: localization
