Repository TomBursch/kitchenowl, pull requests merged in 2025-04, with the labels that each got.

#699 Migrate from pip to uv
  .github/workflows/pytest.yml
  Dockerfile
  backend/.flake8
  backend/.python-version
  backend/Dockerfile
  backend/README.md
  backend/manage.py
  backend/pyproject.toml
  backend/requirements.txt
  backend/uv.lock
  docs/docs/reference/contributing.md
Labels: enhancement

#703 Feature: replace recipe searching with fuzzywuzzy search on local recipes
  kitchenowl/lib/services/transactions/recipe.dart
  kitchenowl/pubspec.lock
  kitchenowl/pubspec.yaml
Labels: enhancement

#705 show recent items only if recentItemsCount greater than zero
  kitchenowl/lib/widgets/shopping_list/sliver_shopinglist_item_view.dart
Labels: bug

#696 Translations update from Hosted Weblate
  backend/templates/l10n/da.json
  backend/templates/l10n/el.json
  backend/templates/l10n/nb_NO.json
  backend/templates/l10n/sk.json
  kitchenowl/lib/l10n/app_bg.arb
  kitchenowl/lib/l10n/app_ca.arb
  kitchenowl/lib/l10n/app_da.arb
  kitchenowl/lib/l10n/app_de.arb
  kitchenowl/lib/l10n/app_el.arb
  kitchenowl/lib/l10n/app_en.arb
  kitchenowl/lib/l10n/app_es.arb
  kitchenowl/lib/l10n/app_nb.arb
  kitchenowl/lib/l10n/app_ru.arb
Labels: localization

#715 Translations update from Hosted Weblate
  kitchenowl/lib/l10n/app_ca_valencia.arb
  kitchenowl/lib/l10n/app_cs.arb
  kitchenowl/lib/l10n/app_de_CH.arb
  kitchenowl/lib/l10n/app_el.arb
  kitchenowl/lib/l10n/app_en_AU.arb
  kitchenowl/lib/l10n/app_fr.arb
  kitchenowl/lib/l10n/app_hu.arb
  kitchenowl/lib/l10n/app_id.arb
  kitchenowl/lib/l10n/app_it.arb
  kitchenowl/lib/l10n/app_lt.arb
  kitchenowl/lib/l10n/app_nl.arb
  kitchenowl/lib/l10n/app_sv.arb
  kitchenowl/lib/l10n/app_ta.arb
  kitchenowl/lib/l10n/app_tr.arb
  kitchenowl/lib/l10n/app_uk.arb
  kitchenowl/lib/l10n/app_vi.arb
Labels: localization

#714 AZ index bar for recipe grid view
  kitchenowl/lib/cubits/recipe_list_cubit.dart
  kitchenowl/lib/models/recipe.dart
  kitchenowl/lib/pages/household_page/recipe_list.dart
  kitchenowl/lib/widgets/index_bar.dart
  kitchenowl/pubspec.lock
  kitchenowl/pubspec.yaml
Labels: enhancement

#716 Code formatting with pre-commit
  backend/.pre-commit-config.yaml
  backend/README.md
  backend/pyproject.toml
  docs/docs/reference/contributing.md
Labels: enhancement

#686 Datetime planner: app
  kitchenowl/lib/config.dart
  kitchenowl/lib/cubits/planner_cubit.dart
  kitchenowl/lib/cubits/recipe_cubit.dart
  kitchenowl/lib/l10n/app_de.arb
  kitchenowl/lib/l10n/app_en.arb
  kitchenowl/lib/models/planner.dart
  kitchenowl/lib/models/recipe.dart
  kitchenowl/lib/pages/household_page/planner.dart
  kitchenowl/lib/pages/recipe_page.dart
  kitchenowl/lib/services/api/planner.dart
  kitchenowl/lib/services/transactions/planner.dart
Labels: enhancement

#510 feat: Add user profile pictures
  kitchenowl/lib/cubits/settings_user_cubit.dart
  kitchenowl/lib/models/user.dart
  kitchenowl/lib/pages/settings_user_page.dart
  kitchenowl/lib/services/api/user.dart
  kitchenowl/lib/widgets/user_image_selector.dart
Labels: enhancement

#722 Recipe UI update
  kitchenowl/lib/helpers/recipe_item_markdown_extension.dart
  kitchenowl/lib/helpers/short_image_markdown_extension.dart
  kitchenowl/lib/pages/household_page/planner.dart
  kitchenowl/lib/pages/household_page/recipe_list.dart
  kitchenowl/lib/pages/recipe_cooking_page.dart
  kitchenowl/lib/services/transactions/recipe.dart
  kitchenowl/lib/widgets/kitchenowl_markdown_body.dart
  kitchenowl/lib/widgets/kitchenowl_markdown_builder.dart
  kitchenowl/lib/widgets/recipe_markdown_body.dart
Labels: enhancement
